server.port=${PORT:8180}

# Railway MySQL Database Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://db:3306/bankingapp}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.generate-ddl=true
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.main.allow-circular-references=true
server.error.include-message=always

# JWT
jwt.secret=${JWT_SECRET:dummy_secret_key_for_local_development_only}
jwt.expiration=86400000
jwt.header=Authorization
jwt.prefix=Bearer

# Spring Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:default}
spring.mail.password=${MAIL_PASSWORD:default}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Geolocation API
geo.api.url=https://api.findip.net/
geo.api.key=${GEO_API_KEY:default}
